#!/bin/sh
set -eo pipefail
stack clean
built_to_path="$(stack build 2>&1 | tee /dev/stderr | sed -En 's/Installing\ executable\ ([a-zA-Z]+) in (.*)/\2\/\1/p')"
ln -f "$built_to_path" xmonad-x86_64-linux
